let pauze = 0
let playJingleBells = false
function spiraal () {
    basic.clearScreen()
    pauze = 100
    basic.pause(pauze)
    led.toggle(0, 0)
    basic.pause(pauze)
    led.toggle(1, 0)
    basic.pause(pauze)
    led.toggle(2, 0)
    basic.pause(pauze)
    led.toggle(3, 0)
    basic.pause(pauze)
    led.toggle(4, 0)
    basic.pause(pauze)
    led.toggle(4, 1)
    basic.pause(pauze)
    led.toggle(4, 2)
    basic.pause(pauze)
    led.toggle(4, 3)
    basic.pause(pauze)
    led.toggle(4, 4)
    basic.pause(pauze)
    led.toggle(3, 4)
    basic.pause(pauze)
    led.toggle(2, 4)
    basic.pause(pauze)
    led.toggle(1, 4)
    basic.pause(pauze)
    led.toggle(0, 4)
    basic.pause(pauze)
    led.toggle(0, 3)
    basic.pause(pauze)
    led.toggle(0, 2)
    basic.pause(pauze)
    led.toggle(0, 1)
    basic.pause(pauze)
    led.toggle(1, 1)
    basic.pause(pauze)
    led.toggle(2, 1)
    basic.pause(pauze)
    led.toggle(3, 1)
    basic.pause(pauze)
    led.toggle(3, 2)
    basic.pause(pauze)
    led.toggle(3, 3)
    basic.pause(pauze)
    led.toggle(2, 3)
    basic.pause(pauze)
    led.toggle(1, 3)
    basic.pause(pauze)
    led.toggle(1, 2)
    basic.pause(pauze)
    led.toggle(2, 2)
}
function JingleBells () {
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Whole))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Whole))
}
basic.forever(function () {
    while (input.lightLevel() > 4) {
        basic.showNumber(3)
        basic.pause(1000)
        basic.showNumber(2)
        basic.pause(1000)
        basic.showNumber(1)
        basic.pause(1000)
        playJingleBells = true
        spiraal()
        basic.showString("Gelukkig Nieuwjaar!")
        playJingleBells = false
        basic.clearScreen()
        basic.pause(10000)
    }
})
basic.forever(function () {
    if (playJingleBells) {
        JingleBells()
    }
})
